channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==8.10.6
  - bbmap=39.01
  - git
  - kma==1.4.9
  - pip
  - pip:
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - jsonschema==v4.18.0a10
    - bifrostlib
    - resfinder
    - -e .
